#!/bin/bash
# ============================================================
# AI Agent Factory — Base Configuration (defaults)
#
# All values use ${VAR:-default} so project overrides take
# precedence when sourced before this file.
#
# Do NOT edit this file for per-project settings.
# Instead, create: projects/<name>/config.sh
# ============================================================

# GitHub repo where agents communicate via Discussions
export GITHUB_OWNER="${GITHUB_OWNER:-clercrobin}"
export GITHUB_REPO="${GITHUB_REPO:-ai-agent-factory}"
export GITHUB_REPO_FULL="${GITHUB_OWNER}/${GITHUB_REPO}"

# The target project agents work on
export TARGET_PROJECT="${TARGET_PROJECT:-$HOME/Workspace/schottentotten}"

# Agent polling interval (seconds) — tune based on your rate limits
# With Claude Code Max, ~60s is safe to avoid hitting limits
export POLL_INTERVAL="${POLL_INTERVAL:-60}"

# Max parallel Claude sessions. Each slot = 1 Claude Code Max subscription.
# With 1 sub: keep at 1 (agents take turns).
# With 2-3 subs: set to 2-3 for true parallelism.
export MAX_PARALLEL_SESSIONS="${MAX_PARALLEL_SESSIONS:-1}"

# Base directory — always relative to this config.sh file
_CONFIG_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Log and state directories (may be overridden by config-loader for projects)
export LOG_DIR="${LOG_DIR:-$_CONFIG_DIR/logs}"
export STATE_DIR="${STATE_DIR:-$_CONFIG_DIR/state}"
mkdir -p "$LOG_DIR"

# Discussion categories (created by setup.sh)
export CAT_TRIAGE="${CAT_TRIAGE:-Triage}"
export CAT_ENGINEERING="${CAT_ENGINEERING:-Engineering}"
export CAT_CODE_REVIEW="${CAT_CODE_REVIEW:-Code Review}"
export CAT_STANDUP="${CAT_STANDUP:-Daily Standup}"

# Agent names (used in Discussion posts)
export AGENT_CTO="${AGENT_CTO:-🎯 Agent CTO}"
export AGENT_SENIOR_ENG="${AGENT_SENIOR_ENG:-👷 Agent Senior Engineer}"
export AGENT_REVIEWER="${AGENT_REVIEWER:-🔎 Agent Code Reviewer}"

# Claude Code settings
export CLAUDE_MODEL="${CLAUDE_MODEL:-sonnet}"  # Use sonnet for most tasks, opus for complex reviews
# Budget per agent invocation (in USD). Claude Code Max doesn't consume API
# credits, so this is mainly a safety rail to prevent runaway sessions.
export CLAUDE_MAX_BUDGET="${CLAUDE_MAX_BUDGET:-5.00}"
# Timeout per Claude invocation (seconds). Implementation tasks need more time.
export CLAUDE_TIMEOUT="${CLAUDE_TIMEOUT:-600}"
