#!/bin/bash
# ============================================================
# 📦 Release Manager Agent — Versioning & changelogs
#
# Manages semantic versioning, generates changelogs from
# merged PRs, and creates release notes. Runs periodically
# or on demand.
# ============================================================
set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
source "$SCRIPT_DIR/../config-loader.sh"
source "$SCRIPT_DIR/../lib/discussions.sh"
source "$SCRIPT_DIR/../lib/state.sh"
source "$SCRIPT_DIR/../lib/robust.sh"

MODE="${1:-changelog}"
AGENT="release-manager"

log() { echo "[$(date '+%H:%M:%S')] [REL] $*"; }

# ────────────────────────────────────────────
# changelog — Generate changelog from recent merges
# ────────────────────────────────────────────
run_changelog() {
    log "📦 Generating changelog..."

    cd "$TARGET_PROJECT"

    # Get commits since last tag or last 50 commits
    local last_tag
    last_tag=$(git describe --tags --abbrev=0 2>/dev/null || echo "")
    local commit_range
    if [ -n "$last_tag" ]; then
        commit_range="${last_tag}..HEAD"
        log "  Commits since $last_tag"
    else
        commit_range="HEAD~50..HEAD"
        log "  Last 50 commits (no tags found)"
    fi

    local commits
    commits=$(git log "$commit_range" --oneline --no-merges 2>/dev/null | head -30)

    if [ -z "$commits" ]; then
        log "  No new commits to document"
        return 0
    fi

    local changelog_prompt
    changelog_prompt=$(load_prompt "release-changelog") || { log "Cannot load prompt"; return 1; }
    changelog_prompt=$(render_prompt "$changelog_prompt" \
        COMMITS "$commits" \
        LAST_TAG "${last_tag:-none}")

    local result
    result=$(safe_claude "$AGENT" "$changelog_prompt" \
    --allowedTools "Read,Glob,Grep") || {
        log "⚠️  Changelog generation failed"
        return 1
    }

    post_discussion "$CAT_ENGINEERING" "📦 Changelog — $(date '+%Y-%m-%d')" \
"$result

---
*Generated by Release Manager. Review before publishing.*" "$AGENT_RELEASE" || true

    log "✅ Changelog posted"
}

case "$MODE" in
    changelog) run_changelog ;;
    *)         echo "Usage: $0 {changelog}"; exit 1 ;;
esac
